In [1]:
import os
os.getcwd()


'C:\\Users\\SONY\\Desktop\\project'

In [2]:
os.chdir("C:/Users/Sony/Desktop/intership-3")
os.getcwd()

'C:\\Users\\SONY\\Desktop\\internship-3'

In [3]:
import numpy as np
import pandas as pd
data=pd.read_csv("bodyfitness.csv")
data

date  stepcount  caloriesburned  hoursofsleep  weight_kg
0    10/6/2019       5464             181             5         66
1    10/7/2019       6041             197             8         66
2    10/8/2019         25               0             5         66
3    10/9/2019       5461             174             4         66
4   10/10/2019       6915             223             5         66
..         ...        ...             ...           ...        ...
84  12/29/2019       3066              99             4         64
85  12/30/2019        177               5             5         64
86  12/31/2019         36               1             3         64
87    1/1/2020        299              10             3         64
88    1/2/2020       1447              47             3         64

[89 rows x 5 columns]

In [4]:
data.isnull().sum()

date              0
stepcount         0
caloriesburned    0
hoursofsleep      0
weight_kg         0
dtype: int64

In [5]:
X=data.iloc[:,:4].values

In [7]:
X

array([['10/6/2019', 5464, 181, 5],
       ['10/7/2019', 6041, 197, 8],
       ['10/8/2019', 25, 0, 5],
       ['10/9/2019', 5461, 174, 4],
       ['10/10/2019', 6915, 223, 5],
       ['10/11/2019', 4545, 149, 6],
       ['10/12/2019', 4340, 140, 6],
       ['10/13/2019', 1230, 38, 7],
       ['10/13/2019', 61, 1, 5],
       ['10/15/2019', 1258, 40, 6],
       ['10/16/2019', 3148, 101, 8],
       ['10/17/2019', 4687, 152, 5],
       ['10/18/2019', 4732, 150, 6],
       ['10/19/2019', 3519, 113, 7],
       ['10/20/2019', 1580, 49, 5],
       ['10/21/2019', 2822, 86, 6],
       ['10/22/2019', 181, 6, 8],
       ['10/23/2019', 3158, 99, 5],
       ['10/24/2019', 4383, 143, 4],
       ['10/25/2019', 3881, 125, 5],
       ['10/26/2019', 4037, 129, 6],
       ['10/27/2019', 202, 6, 8],
       ['10/28/2019', 292, 9, 5],
       ['10/29/2019', 330, 10, 6],
       ['10/30/2019', 2209, 72, 5],
       ['10/31/2019', 4550, 150, 8],
       ['11/1/2019', 4435, 141, 5],
       ['11/2/2019', 4779, 156,

In [8]:
y=data.iloc[:,-1].values
y

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64], dtype=int64)

In [9]:
from sklearn.preprocessing import LabelEncoder
lb1=LabelEncoder()
X[:,-1]

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3], dtype=object)

In [10]:
X[:,-1]=lb1.fit_transform(X[:,-1])

In [11]:
X

array([['10/6/2019', 5464, 181, 3],
       ['10/7/2019', 6041, 197, 6],
       ['10/8/2019', 25, 0, 3],
       ['10/9/2019', 5461, 174, 2],
       ['10/10/2019', 6915, 223, 3],
       ['10/11/2019', 4545, 149, 4],
       ['10/12/2019', 4340, 140, 4],
       ['10/13/2019', 1230, 38, 5],
       ['10/13/2019', 61, 1, 3],
       ['10/15/2019', 1258, 40, 4],
       ['10/16/2019', 3148, 101, 6],
       ['10/17/2019', 4687, 152, 3],
       ['10/18/2019', 4732, 150, 4],
       ['10/19/2019', 3519, 113, 5],
       ['10/20/2019', 1580, 49, 3],
       ['10/21/2019', 2822, 86, 4],
       ['10/22/2019', 181, 6, 6],
       ['10/23/2019', 3158, 99, 3],
       ['10/24/2019', 4383, 143, 2],
       ['10/25/2019', 3881, 125, 3],
       ['10/26/2019', 4037, 129, 4],
       ['10/27/2019', 202, 6, 6],
       ['10/28/2019', 292, 9, 3],
       ['10/29/2019', 330, 10, 4],
       ['10/30/2019', 2209, 72, 3],
       ['10/31/2019', 4550, 150, 6],
       ['11/1/2019', 4435, 141, 3],
       ['11/2/2019', 4779, 156,

In [12]:
#onehotencoding

In [13]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder()
x1=X[:,3].reshape((-1,1))
z=oh.fit_transform(x1).toarray()
z

array([[0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 

In [14]:
#spliting the data into traning and testing

In [15]:
X=data['stepcount']
y=data['caloriesburned']

In [16]:
X

0     5464
1     6041
2       25
3     5461
4     6915
      ... 
84    3066
85     177
86      36
87     299
88    1447
Name: stepcount, Length: 89, dtype: int64

In [17]:
y

0     181
1     197
2       0
3     174
4     223
     ... 
84     99
85      5
86      1
87     10
88     47
Name: caloriesburned, Length: 89, dtype: int64

In [ ]:
#spliting data into traning and testing

In [18]:
from sklearn.model_selection import train_test_split  #train_test_split splits arrays or matrices into random train and test subsets. 
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.4,random_state =1)

In [19]:
X_train

58    4064
15    2822
86      36
80     518
26    4435
87     299
55    3608
4     6915
52     995
21     202
78     651
3     5461
81    5537
30     539
56     774
42     705
47    4421
51     493
66     799
24    2209
8       61
17    3158
0     5464
82    4108
57    1421
22     292
61    1867
63    2374
7     1230
85     177
13    3519
74     221
14    1580
29    2255
28    1831
11    4687
18    4383
20    4037
50     546
25    4550
6     4340
71    1231
76    3575
1     6041
16     181
64    2909
79     753
5     4545
75    6500
9     1258
72    1696
12    4732
37     614
Name: stepcount, dtype: int64

In [20]:
y_train

58    131
15     86
86      1
80     16
26    141
87     10
55    116
4     223
52     32
21      6
78     21
3     174
81    180
30     17
56     23
42     22
47    146
51     17
66     25
24     72
8       1
17     99
0     181
82    138
57     44
22      9
61     60
63     76
7      38
85      5
13    113
74      7
14     49
29     72
28     57
11    152
18    143
20    129
50     16
25    150
6     140
71     39
76    116
1     197
16      6
64     93
79     28
5     149
75    213
9      40
72     55
12    150
37     19
Name: caloriesburned, dtype: int64

In [21]:
X_train = X_train.values.reshape((-1,1))

In [22]:
X_train

array([[4064],
       [2822],
       [  36],
       [ 518],
       [4435],
       [ 299],
       [3608],
       [6915],
       [ 995],
       [ 202],
       [ 651],
       [5461],
       [5537],
       [ 539],
       [ 774],
       [ 705],
       [4421],
       [ 493],
       [ 799],
       [2209],
       [  61],
       [3158],
       [5464],
       [4108],
       [1421],
       [ 292],
       [1867],
       [2374],
       [1230],
       [ 177],
       [3519],
       [ 221],
       [1580],
       [2255],
       [1831],
       [4687],
       [4383],
       [4037],
       [ 546],
       [4550],
       [4340],
       [1231],
       [3575],
       [6041],
       [ 181],
       [2909],
       [ 753],
       [4545],
       [6500],
       [1258],
       [1696],
       [4732],
       [ 614]], dtype=int64)

In [23]:
y_train

58    131
15     86
86      1
80     16
26    141
87     10
55    116
4     223
52     32
21      6
78     21
3     174
81    180
30     17
56     23
42     22
47    146
51     17
66     25
24     72
8       1
17     99
0     181
82    138
57     44
22      9
61     60
63     76
7      38
85      5
13    113
74      7
14     49
29     72
28     57
11    152
18    143
20    129
50     16
25    150
6     140
71     39
76    116
1     197
16      6
64     93
79     28
5     149
75    213
9      40
72     55
12    150
37     19
Name: caloriesburned, dtype: int64