In [7]:
import os
os.getcwd()


'C:\\Users\\SONY\\Desktop\\internship-3'

In [8]:
os.chdir("C:/Users/SONY/Desktop/internship-3")
os.getcwd()import numpy as np

'C:\\Users\\SONY\\Desktop\\internship-3'

In [9]:
import numpy as np
import pandas as pd
data=pd.read_csv("bodyfitness.csv")
data

date  stepcount  caloriesburned  hoursofsleep  weight_kg
0    10/6/2019       5464             181             5         66
1    10/7/2019       6041             197             8         66
2    10/8/2019         25               0             5         66
3    10/9/2019       5461             174             4         66
4   10/10/2019       6915             223             5         66
..         ...        ...             ...           ...        ...
84  12/29/2019       3066              99             4         64
85  12/30/2019        177               5             5         64
86  12/31/2019         36               1             3         64
87    1/1/2020        299              10             3         64
88    1/2/2020       1447              47             3         64

[89 rows x 5 columns]

In [10]:
data.isnull().sum()

date              0
stepcount         0
caloriesburned    0
hoursofsleep      0
weight_kg         0
dtype: int64

In [11]:
X=data.iloc[:,:4].values

In [12]:
X

array([['10/6/2019', 5464, 181, 5],
       ['10/7/2019', 6041, 197, 8],
       ['10/8/2019', 25, 0, 5],
       ['10/9/2019', 5461, 174, 4],
       ['10/10/2019', 6915, 223, 5],
       ['10/11/2019', 4545, 149, 6],
       ['10/12/2019', 4340, 140, 6],
       ['10/13/2019', 1230, 38, 7],
       ['10/13/2019', 61, 1, 5],
       ['10/15/2019', 1258, 40, 6],
       ['10/16/2019', 3148, 101, 8],
       ['10/17/2019', 4687, 152, 5],
       ['10/18/2019', 4732, 150, 6],
       ['10/19/2019', 3519, 113, 7],
       ['10/20/2019', 1580, 49, 5],
       ['10/21/2019', 2822, 86, 6],
       ['10/22/2019', 181, 6, 8],
       ['10/23/2019', 3158, 99, 5],
       ['10/24/2019', 4383, 143, 4],
       ['10/25/2019', 3881, 125, 5],
       ['10/26/2019', 4037, 129, 6],
       ['10/27/2019', 202, 6, 8],
       ['10/28/2019', 292, 9, 5],
       ['10/29/2019', 330, 10, 6],
       ['10/30/2019', 2209, 72, 5],
       ['10/31/2019', 4550, 150, 8],
       ['11/1/2019', 4435, 141, 5],
       ['11/2/2019', 4779, 156,

In [13]:
y=data.iloc[:,-1].values
y

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64], dtype=int64)

In [14]:
from sklearn.preprocessing import LabelEncoder
lb1=LabelEncoder()
X[:,-1]

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3], dtype=object)

In [15]:
X[:,-1]=lb1.fit_transform(X[:,-1])

In [16]:
X

array([['10/6/2019', 5464, 181, 3],
       ['10/7/2019', 6041, 197, 6],
       ['10/8/2019', 25, 0, 3],
       ['10/9/2019', 5461, 174, 2],
       ['10/10/2019', 6915, 223, 3],
       ['10/11/2019', 4545, 149, 4],
       ['10/12/2019', 4340, 140, 4],
       ['10/13/2019', 1230, 38, 5],
       ['10/13/2019', 61, 1, 3],
       ['10/15/2019', 1258, 40, 4],
       ['10/16/2019', 3148, 101, 6],
       ['10/17/2019', 4687, 152, 3],
       ['10/18/2019', 4732, 150, 4],
       ['10/19/2019', 3519, 113, 5],
       ['10/20/2019', 1580, 49, 3],
       ['10/21/2019', 2822, 86, 4],
       ['10/22/2019', 181, 6, 6],
       ['10/23/2019', 3158, 99, 3],
       ['10/24/2019', 4383, 143, 2],
       ['10/25/2019', 3881, 125, 3],
       ['10/26/2019', 4037, 129, 4],
       ['10/27/2019', 202, 6, 6],
       ['10/28/2019', 292, 9, 3],
       ['10/29/2019', 330, 10, 4],
       ['10/30/2019', 2209, 72, 3],
       ['10/31/2019', 4550, 150, 6],
       ['11/1/2019', 4435, 141, 3],
       ['11/2/2019', 4779, 156,

In [17]:
#onehotencoding

In [18]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder()
x1=X[:,3].reshape((-1,1))
z=oh.fit_transform(x1).toarray()
z

array([[0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 

In [19]:
#spliting the data into traning and testing

In [20]:
X=data['stepcount']
y=data['caloriesburned']

In [21]:
X

0     5464
1     6041
2       25
3     5461
4     6915
      ... 
84    3066
85     177
86      36
87     299
88    1447
Name: stepcount, Length: 89, dtype: int64

In [22]:
y

0     181
1     197
2       0
3     174
4     223
     ... 
84     99
85      5
86      1
87     10
88     47
Name: caloriesburned, Length: 89, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split  #train_test_split splits arrays or matrices into random train and test subsets. 
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.4,random_state =1)

In [24]:
X_train

58    4064
15    2822
86      36
80     518
26    4435
87     299
55    3608
4     6915
52     995
21     202
78     651
3     5461
81    5537
30     539
56     774
42     705
47    4421
51     493
66     799
24    2209
8       61
17    3158
0     5464
82    4108
57    1421
22     292
61    1867
63    2374
7     1230
85     177
13    3519
74     221
14    1580
29    2255
28    1831
11    4687
18    4383
20    4037
50     546
25    4550
6     4340
71    1231
76    3575
1     6041
16     181
64    2909
79     753
5     4545
75    6500
9     1258
72    1696
12    4732
37     614
Name: stepcount, dtype: int64

In [25]:
y_train

58    131
15     86
86      1
80     16
26    141
87     10
55    116
4     223
52     32
21      6
78     21
3     174
81    180
30     17
56     23
42     22
47    146
51     17
66     25
24     72
8       1
17     99
0     181
82    138
57     44
22      9
61     60
63     76
7      38
85      5
13    113
74      7
14     49
29     72
28     57
11    152
18    143
20    129
50     16
25    150
6     140
71     39
76    116
1     197
16      6
64     93
79     28
5     149
75    213
9      40
72     55
12    150
37     19
Name: caloriesburned, dtype: int64

In [26]:
X_train = X_train.values.reshape((-1,1))

In [27]:
X_train

array([[4064],
       [2822],
       [  36],
       [ 518],
       [4435],
       [ 299],
       [3608],
       [6915],
       [ 995],
       [ 202],
       [ 651],
       [5461],
       [5537],
       [ 539],
       [ 774],
       [ 705],
       [4421],
       [ 493],
       [ 799],
       [2209],
       [  61],
       [3158],
       [5464],
       [4108],
       [1421],
       [ 292],
       [1867],
       [2374],
       [1230],
       [ 177],
       [3519],
       [ 221],
       [1580],
       [2255],
       [1831],
       [4687],
       [4383],
       [4037],
       [ 546],
       [4550],
       [4340],
       [1231],
       [3575],
       [6041],
       [ 181],
       [2909],
       [ 753],
       [4545],
       [6500],
       [1258],
       [1696],
       [4732],
       [ 614]], dtype=int64)

In [28]:
y_train

58    131
15     86
86      1
80     16
26    141
87     10
55    116
4     223
52     32
21      6
78     21
3     174
81    180
30     17
56     23
42     22
47    146
51     17
66     25
24     72
8       1
17     99
0     181
82    138
57     44
22      9
61     60
63     76
7      38
85      5
13    113
74      7
14     49
29     72
28     57
11    152
18    143
20    129
50     16
25    150
6     140
71     39
76    116
1     197
16      6
64     93
79     28
5     149
75    213
9      40
72     55
12    150
37     19
Name: caloriesburned, dtype: int64

In [29]:
#traning and testing the model

In [30]:
from sklearn import linear_model as lm
model=lm.LinearRegression()
results=model.fit(X_train,y_train) 

In [31]:
accuracy = model.score(X_train, y_train)
print('Accuracy of the model:', accuracy)

Accuracy of the model: 0.9992075124080033


In [32]:
print('intercept:', model.intercept_)
print('slope:', model.coef_)

intercept: -0.8533961907337755
slope: [0.03258063]


In [33]:
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
X_test

60    5934
70     437
53    1163
54    6676
77    4061
73    4921
59    2725
41    4136
45    4275
38    3149
39    4005
31    5464
68    3941
27    4779
88    1447
49    5195
10    3148
2       25
36    6314
69    7422
46    5999
19    3881
83    5376
35    4033
33    4068
32    6041
44     269
65    1648
62    3721
67    7102
34    4683
40    4880
48    6930
23     330
84    3066
43     570
Name: stepcount, dtype: int64

In [35]:
X_test = X_test.values.reshape((-1,1))

In [36]:
predictions = model.predict(X_test)
print('predicted caloriesburned:',predictions, sep = '\n')

predicted caloriesburned:
[ 1.92480065e+02  1.33843393e+01  3.70378770e+01  2.16654893e+02
  1.31456544e+02  1.59475886e+02  8.79288218e+01  1.33900091e+02
  1.38428799e+02  1.01743009e+02  1.29632029e+02  1.77167169e+02
  1.27546868e+02  1.54849437e+02  4.62907761e+01  1.68402979e+02
  1.01710428e+02 -3.88804297e-02  2.04860704e+02  2.40960043e+02
  1.94597806e+02  1.25592031e+02  1.74300073e+02  1.30544286e+02
  1.31684608e+02  1.95966192e+02  7.91079340e+00  5.28394828e+01
  1.20379130e+02  2.30534241e+02  1.51721696e+02  1.58140080e+02
  2.24930373e+02  9.89821186e+00  9.90388167e+01  1.77175632e+01]


In [37]:
y_test

60    194
70     14
53     35
54    220
77    129
73    158
59     86
41    137
45    145
38    101
39    139
31    181
68    125
27    156
88     47
49    167
10    101
2       0
36    193
69    243
46    192
19    125
83    176
35    137
33    131
32    197
44      9
65     53
62    121
67    227
34    154
40    164
48    234
23     10
84     99
43     17
Name: caloriesburned, dtype: int64

In [38]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.scatter(y_test, predictions)

In [39]:
y_pred = model.intercept_ + model.coef_ * X_test
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 1.92480065e+02]
 [ 1.33843393e+01]
 [ 3.70378770e+01]
 [ 2.16654893e+02]
 [ 1.31456544e+02]
 [ 1.59475886e+02]
 [ 8.79288218e+01]
 [ 1.33900091e+02]
 [ 1.38428799e+02]
 [ 1.01743009e+02]
 [ 1.29632029e+02]
 [ 1.77167169e+02]
 [ 1.27546868e+02]
 [ 1.54849437e+02]
 [ 4.62907761e+01]
 [ 1.68402979e+02]
 [ 1.01710428e+02]
 [-3.88804297e-02]
 [ 2.04860704e+02]
 [ 2.40960043e+02]
 [ 1.94597806e+02]
 [ 1.25592031e+02]
 [ 1.74300073e+02]
 [ 1.30544286e+02]
 [ 1.31684608e+02]
 [ 1.95966192e+02]
 [ 7.91079340e+00]
 [ 5.28394828e+01]
 [ 1.20379130e+02]
 [ 2.30534241e+02]
 [ 1.51721696e+02]
 [ 1.58140080e+02]
 [ 2.24930373e+02]
 [ 9.89821186e+00]
 [ 9.90388167e+01]
 [ 1.77175632e+01]]
